### PR TITLE
CI: Simplify redundant "buildArch" and "BUILD_ARCH" variables into one variable

### PR DESCRIPTION
**Pull request by DeeDeeG**
### Description of the Change

Use `BUILD_ARCH` everywhere. (Eliminate `buildArch`.)

I'm doing this rather than what we were doing before, which was setting `buildArch`, then setting `BUILD_ARCH` equal to `buildArch` and then using the value from `BUILD_ARCH`. This was unnecessarily complicated and 100% redundant.

### Alternate Designs

None.

### Possible Drawbacks

None.

### Verification Process

CI passes. Node 32-bit is still used on the Windows 32-bit jobs, Node 64-bit is still used for the Windows 64-bit jobs. (`buildArch` and `BUILD_ARCH` haven't ever been set on OSes other than Windows.)

### Release Notes

N/A

### CODE REVIEW

**Review by aminya — CHANGES_REQUESTED** [review]
Instead of changing this code all over the place, rename `buildArch` to `BUILD_ARCH`.

**Comment by DeeDeeG** [comment]
This is updated now.

**Comment by DeeDeeG** [comment]
IMO `buildArch` is nicer, by the way. Went with BUILD_ARCH because it's not really worth getting hung up on, but that would be my preference.

**Review by aminya — CHANGES_REQUESTED** [review]
The CI fails now

**Comment by DeeDeeG** [comment]
I accidentally posted these two PRs from my fork.

Secret variables aren't available to builds of forks. `GITHUB_TOKEN` is secret, trying to install `vscode-ripgrep` hits GitHub API rate-limiting. CI fails.

I can re-post both of these PRs from branches at this repo if you want.

**Comment by aminya** [comment]
You can add your own GitHub token.

**Comment by DeeDeeG** [comment]
I can't make CI run here unless a non-encrypted `GITHU_TOKEN` variable is available on the Pull Requests pipeline.

By the way, figuring this out now might be a good idea so that others can contribute.

I think this would work:
- Add an unencrypted (non-secret) `GITHUB_TOKEN` to the main variable group that is shared by all pipelines.
  - Make sure this token has no permissions added, just API access.

And optionally:
- Add an encrypted (secret) `GITHUB_TOKEN` to a separate variable group
  - Only add this to the Release Branch Build and Nightly Release pipelines
  - This token should have enough permissions to modify our repository, so we can make GitHub Releases with it

**Comment by DeeDeeG** [comment]
By the way, I did add my own token directly to the Pull Request pipeline. It didn't seem to fix anything.

I think the secret one from the variable group takes precedence, and then because secret ones aren't available to the CI run, neither is available to the CI run.

**Comment by DeeDeeG** [comment]
@aminya do you mind if I modify the variable groups to set this up? I already did that at my personal fork, and it seems to be working.

**Comment by DeeDeeG** [comment]
I still don't have permission to modify the variable groups. If you can add me to able to do that, that would be great.

**Comment by aminya** [comment]
I added the token. Let's see if this passes.

**Comment by DeeDeeG** [comment]
It seems to have at least gotten past the build jobs and onto the testing jobs. :+1:

**Review by aminya — APPROVED** [review]
Thank you! 

I wanted to do these miscellaneous things after https://github.com/atom/atom/pull/21081 is merged. I will cherry-pick the commit.

**Pull request merged**
