### PR TITLE
⬆️ electron@6.1.12

### PR DESCRIPTION
**Pull request by aminya**
### Description of the change

This updates Electron to 6.1.12. 

Ref: https://github.com/atom/atom/pull/21079

### Release Notes
- This updates Electron to 6.1.12.

### CODE REVIEW

**Comment by aminya** [comment]
I merged master to this. I chose all the changes from our side.

**Comment by aminya** [comment]
@DeeDeeG Could you update this branch from our master and merge it?

**Comment by DeeDeeG** [comment]
Hi, I did this just recently: https://github.com/DeeDeeG/atom/commits/electron-6-atom-ide-community

I think that's what you are looking for. I can push the commits here.

**Comment by aminya** [comment]
Is this ready? Can we merge?

**Comment by DeeDeeG** [comment]
I'm ready for the "Windows Renderer Tests 2" to finish, now that I pressed "Re-run Failed jobs".

**Comment by DeeDeeG** [comment]
I'm getting unlucky with the timeouts today.

**Comment by DeeDeeG** [comment]
Passing CI, woo! Only took four runs... Hope that's not the pattern going forward!

Ready to go!!!

**Comment by aminya** [comment]
Yay! 🎉

**Pull request merged**
