### PR TITLE
Set up lighthouse artifact feed for our fork

### PR DESCRIPTION
**Pull request by DeeDeeG**
### Identify the Bug

https://github.com/atom-ide-community/atom/issues/1#issuecomment-653903786

https://github.com/atom-ide-community/atom/pull/11#issuecomment-653999116

### Description of the Change

Rather than hard-coding upstream Atom's feed ID, set it with an environment variable. We can configure this in Azure DevOps so that our environment variable points to our fork's (technically our Azure DevOps oganization's) artifact feed.

Having this artifact feed set up properly can save about 10 minutes per OS.

### Alternate Designs

- Just hard-code our ID in place of upstream's.

- We could also make separate `.yml` config files for our CI entirely I guess, and stop using the original ones. This avoids the possibility of merge conflicts. But I think that's not worth the hassle and the mess of files it would make. Upstream ahrdly ever updates their CI config, and I think we would likely want to track their changes if they do.

### Possible Drawbacks

Some people don't like to save time. (Just kidding).

I guess with caching you have to make sure it updated when you want it to. So keep an eye out that it doesn't restore a cache when it shouldn't (i.e. when something in the repo changed and `node_modules` needs to be rebuilt).

### Verification Process

Successful node_modules restoration on my personal fork: https://dev.azure.com/DeeDeeG/b/_build/results?buildId=67&view=logs&j=4fbced83-508e-5fe0-c978-5c71ec0fc506&t=96ecc7f1-cdb5-518e-2cb8-d9226cce9313

### Release Notes

N/A

### CODE REVIEW

**Comment by DeeDeeG** [comment]
Reminder to find our Azure DevOps organization's default feed id from here:

https://feeds.dev.azure.com/atomcommunity/_apis/packaging/feeds

(Next to `fullyQualifiedID:`)

And either set it as the value for an environment variable `ARTIFACT_FEED` for each feed... Or hard-code this in place of upstream's feed ID.

`description:` should have the value "Default feed for atomcommunity" or else it is the wrong feed. (There are [organization scoped feeds, and project scoped feeds](https://docs.microsoft.com/azure/devops/artifacts/feeds/project-scoped-feeds). Lighthouse caching only works with organization scoped feeds. The "default feed for atomcommunity" is our organization scoped feed.)

**Comment by DeeDeeG** [comment]
Also, as mentioned in #10 and #11, we are looking at the official Cache task, which is officially supported by Azure DevOps, as opposed to the Lighthouse Universal Packages/artifact feeds solution, which is an unofficial "DevLabs" project.

https://github.com/microsoft/azure-pipelines-artifact-caching-tasks/issues/40#issuecomment-619713944
https://github.com/microsoft/azure-pipelines-artifact-caching-tasks/issues/33#issuecomment-580041758

This is a good thing to get working first, though.

**Comment by aminya** [comment]
It seems that it is building from the ground up 🤔

**Comment by aminya** [comment]
> Rather than hard-coding upstream Atom's feed ID, set it with an environment variable. We can configure this in Azure DevOps so that our environment variable points to our fork's (technically our Azure DevOps oganization's) artifact feed.

Where can I find this feed ID?

**Comment by DeeDeeG** [comment]
> Where can I find this feed ID?

Visit this URL in a browser where you are logged into Azure DevOps: https://feeds.dev.azure.com/atomcommunity/_apis/packaging/feeds

This page serves a [json](https://en.wikipedia.org/wiki/JSON#Example) structured data file. In it there should be a `key:value` pair `fullyQualifiedId:${the_id_you_are_looking_for}`

If you have more than one `fullyQualifiedId` in the json file, it means you added a project scoped artifact feed at some point. In that case, look for the feed with this `key:value` pair: `description:Default feed for atomcommunity`

(Their server will apparently check your cookies/web session with Azure DevOps to make sure you are an authorized administrator for the "atomcommunity" Azure DevOps organization. When I try to visit this page, it shows the following error: `"TF400813: The user 'Windows Live ID\\${my_email_here}' is not authorized to access this resource."`)

(Maybe this is too much of an explanation, but I hope to make it very clear for anyone else who might be reading this and hoping to understand how to set up Azure DevOps.)

**Comment by DeeDeeG** [comment]
I am working on a total replacement for the Lighthouse caching thing. Seems promising so far, but I can't say for 100% sure that it will work:

https://dev.azure.com/DeeDeeG/b/_build/results?buildId=70&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=d33d5f04-2c42-5a66-3d48-399912433e22

Similar idea to #11

**Comment by aminya** [comment]
I added the ID. Let's see how this runs.

**Comment by aminya** [comment]
I merged this to test it on master.

**Pull request merged**
