### PR TITLE
Bump electron to 6

### PR DESCRIPTION
**Pull request by aminya**
We will not merge this. This is just an experiment, so do not review this.

Differences with upstream:
~- I bumped vscode-ripgrep from 1.2.5 to 1.8: https://github.com/atom/atom/pull/21056~
- Etch bumped to 0.14
- electron-link bumped
- bumped settings view 
- bumped find and replace
- package symbolic link PR merged
- use apm node-12
- bumped scrollbar style
- We use clang 9 on Linux
- Our CI is faster and up to date.

### CODE REVIEW

**Comment by aminya** [comment]
@DeeDeeG Does using your apm branch help this?

**Comment by DeeDeeG** [comment]
This (electron 6) should be working just as well here as it is upstream. Apm updates should have no impact unless we are trying to run with Visual Studio. The Node 12 apm bump has no imoact on this.

Remaining issues that I don't know how to fix:

- Slow GPU process on my computer (apparently not a problem on most hardware).
- "Find in Project" --> "Find and Replace" button doesn't do anything.

**Comment by aminya** [comment]
Find and replace tests fail on this one. But I want to test them manually. Maybe the tests are out of date as well.

**Comment by aminya** [comment]
I downloaded the windows artifact from here: https://dev.azure.com/atomcommunity/atomcommunity/_build/results?buildId=317&view=artifacts&type=publishedArtifacts

Find and replace works for me. 

However, in the settings view I cannot scroll using trackpad gestures.

**Comment by aminya** [comment]
@DeeDeeG I want to test your apm branch on this. How would I do that?

**Comment by aminya** [comment]
I cannot search packages in the settings view
image

**Comment by aminya** [comment]
I am going to close this as the upstream pull request is updated.

**Comment by DeeDeeG** [comment]
I am willing to merge this here and deal with anything that comes up if it will help convince upstream to merge it.

Yet, is complicates our other PRs. But somebody's going to have to do it eventually. I think if we want to show upstream we're serious, this could be something to do here first.

Any thoughts? Agree/disagree? (I wonder why upstream isn't merging it anyhow... Hmm. It seems ready to me.)

**Comment by aminya** [comment]
I was thinking about that. Let me do it myself. I will delete some of these useless branches and will merge it!

I love the Electron 7 idea!  My next big thing is #67. You can work on electron 7 in parallel.

**Pull request closed without merging**
