### PR TITLE
CI: Cache/restore the npm network/package cache

### PR DESCRIPTION
**Pull request by DeeDeeG**
This saves/restores the caches of just the packages.
(Not the installed and/or compiled versions, which are in node_modules;
We have already been caching those for some time now.)

<details><summary>Requirements for Adding, Changing, or Removing a Feature</summary>

### Requirements for Adding, Changing, or Removing a Feature

* Fill out the template below. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* The pull request must contribute a change that has been endorsed by the maintainer team. See details in the template below.
* The pull request must update the test suite to exercise the updated functionality. For guidance, please see <https://flight-manual.atom.io/hacking-atom/sections/writing-specs/>.
* After you create the pull request, all status checks must be pass before a maintainer reviews your contribution. For more details, please see <https://github.com/atom/.github/tree/master/CONTRIBUTING.md#pull-requests>.

</details>

### Issue or RFC Endorsed by Atom's Maintainers

Discussed here: https://github.com/atom-ide-community/atom/pull/33#issuecomment-656477312

### Description of the Change

Cache not only the post-install `node_modules` folder, which we have been caching for some time now, but also the pre-install package/network cache that `npm` stores the packages from the registry in. This cache is there so you don't have to wait for your network connection to the registry, but can pull previously fetched packages straight from the hard disk.

In this case, caching it moves the network hit to "somewhere else in the Azure DevOps servers", which should hopefully be faster than hitting the npm registry.

### Alternate Designs

Don't do this, and keep doing what we've been doing.

I'm trying this because I want to see if it is, in fact, faster. It's an experiment.

### Possible Drawbacks

Could be slower than just hitting the npm package registry.

Or this could somehow be unreliable or add undesirable complexity. However, the `Cache@2` task is very well-behaved, being more likely to gracefully step out of the way and not do anything if it can't fully restore a cache. And npm fairly heavily validates everything that goes into/come out of the cache. So hopefully there's no issue with keeping the network/package cache around for multiple runs.

### Verification Process

Watch CI and see what happens.

### Release Notes

N/A

### CODE REVIEW

**Comment by DeeDeeG** [comment]
For the historical record: to the best of my knowledge, this PR was at commit https://github.com/atom-ide-community/atom/commit/861ded20c5cf58b55b46646c1078f754f40f2f23 before #46 was merged into `master, and before this PR was then rebased on top of `master` again.

For convenience (and to keep that commit and its parents from being pruned), this branch exists to mark said commit, at least for now: https://github.com/atom-ide-community/atom/tree/pr-43-before-pr-46

**Comment by DeeDeeG** [comment]
I'm not sure this had any benefit. I think we can close?

**Comment by aminya** [comment]
Let's wait until we merge #50. I want to test and see if any time is saved.

**Comment by aminya** [comment]
This does not seem to have any benefits. I will close this.

**Pull request closed without merging**
