### PR TITLE
Fix Azure

### PR DESCRIPTION
**Pull request by aminya**
To test azure pipeline

### CODE REVIEW

**Comment by DeeDeeG** [comment]
Pasting the error here for posterity:
```console
A task is missing. The pipeline references a task called
'1ESLighthouseEng.PipelineArtifactCaching.RestoreCacheV1.RestoreCache'. This usually
indicates the task isn't installed, and you may be able to install it from the Marketplace:
https://marketplace.visualstudio.com. (Task version 1, job 'Windows', step ''.)
```

For the record, (as mentioned in #1) I think installing [this artifact caching task thing](https://marketplace.visualstudio.com/items?itemName=1ESLighthouseEng.PipelineArtifactCaching) to the `atomcommunity` Azure DevOps org should get rid of this error message.

**Comment by aminya** [comment]
I installed the after-mentioned package. Let's see

**Comment by DeeDeeG** [comment]
I got the same `node-gyp rebuild` error when building `@atom/watcher`. So I think that's a genuine bug with the Atom dependencies.

Probably the wrong V8 version/the wrong Node version or wrong Electron version, or something.

**Comment by aminya** [comment]
> I got the same `node-gyp rebuild` error when building `@atom/watcher`. So I think that's a genuine bug with the Atom dependencies.
> 
> Probably the wrong V8 version/the wrong Node version or wrong Electron version, or something.

That seems strange. The upstream repo does not have this issue
https://github.visualstudio.com/9e67709c-1fe5-47f2-8cf6-4902878a11f5/_build/results?buildId=73864

**Comment by DeeDeeG** [comment]
The CI caches successful `npm install` results (`node_modules`) so maybe that's why.

---

Explanation/research:

I think there's an old `@atom/watcher` in `[repo root]/package-lock.json`. Leading to outdated `nan` which fails on some versions of Node 12. https://github.com/nodejs/nan/issues/849#issuecomment-486899010 https://github.com/nodejs/nan/issues/849#issuecomment-486907168

This was fixed here: https://github.com/atom/watcher/pull/234 (released in `@atom/watcher` v1.3.2+. Actually, [there is](https://github.com/atom/watcher/releases) [no v1.3.2](https://www.npmjs.com/package/@atom/watcher), so v1.3.3+ I guess?)

But `[repo root]/package-lock.json` still has an older version of `@atom/watcher`: https://github.com/atom/atom/blob/aa3c34bedb361e09a5068dce9620b460a20ca3fb/package-lock.json#L55 (v1.3.1).

---

So I'm pretty sure it's an upstream Atom bug. Guess it's time to post an issue there... and if we get impatient we can patch it here.

**Comment by aminya** [comment]
In triggers > YAML > the default agent was Ubuntu. I noticed upstream is using Windows, while for us it is shown as Ubuntu.

**Comment by DeeDeeG** [comment]
Interesting. Well, checking out the git repo and doing `npm install` should work cross-platform. And then the later steps get run in their specified OSes. I think we can proceed trying to make this work in Ubuntu for now.

**Comment by aminya** [comment]
> Interesting. Well, checking out the git repo and doing `npm install` should work cross-platform. And then the later steps get run in their specified OSes. I think we can proceed trying to make this work in Ubuntu for now.
> 
> Edit: It got past the `npm install` step under Windows... I don't understand why... But it did. Maybe that missing V8 feature isn't used the same way on Linux as on Windows?

That's something to consider for later. I guess it is more important to get this working first :smile:

**Comment by DeeDeeG** [comment]
I found some docs for getting this to run automatically via closer GitHub integration, rather than just manually.

https://www.azuredevopslabs.com/labs/vstsextend/github-azurepipelines/#task-1-installing-azure-pipelines-from-github-marketplace

**Comment by DeeDeeG** [comment]
I found the main Azure docs, but there's a lot of them:

https://docs.microsoft.com/en-us/azure/devops/pipelines/?view=azure-devops

https://docs.microsoft.com/en-us/azure/devops/?view=azure-devops

**Comment by DeeDeeG** [comment]
This has to be the docs we're looking for: https://docs.microsoft.com/azure/devops/pipelines/repos/github

**Comment by DeeDeeG** [comment]
I figured out why it works in Windows and not Ubuntu.

There are lines like this, with backslashes in some paths:

[`cd script\vsts`](https://github.com/atom/atom/blob/0fe5533ab32fd9e5576d61624ba54b40acf00052/script/vsts/pull-requests.yml#L9)

The backslash is treated as an escape character on Ubuntu/macOS, so the `cd` doesn't happen:

[`sh: line 1: cd: scriptvsts: No such file or directory`](https://dev.azure.com/DeeDeeG/b/_build/results?buildId=40&view=logs&j=0d2f351d-5899-57e2-0cb5-b37eb91cc930&t=4bcffbf6-507a-564a-0cc4-d6754c0b024f&l=12)

Changing the backslashes to forward-slashes also works, as an alternative to forcing Windows.
https://dev.azure.com/DeeDeeG/b/_build/results?buildId=44&view=logs&j=0d2f351d-5899-57e2-0cb5-b37eb91cc930&t=4bcffbf6-507a-564a-0cc4-d6754c0b024f

(^ This is a successful run of the GetReleaseVersion job, on Ubuntu 16.04.)

I'd like to post an issue/maybe a PR at upstream about this.

**Comment by aminya** [comment]
@DeeDeeG Awesome! One you made the PR we can merge it here.

**Comment by DeeDeeG** [comment]
Whoops, I just saw your comment. Yeah, trying to get this accepted upstream.

Issue: https://github.com/atom/atom/issues/21020

**Pull request merged**
