### PR TITLE
support ES6 default require for packages

### PR DESCRIPTION
**Pull request by aminya**
#### In short: 
This allows loading the packages that are Es module and export their function wrapped in a default object. This is the case for any package that uses Babel 6, Babel 7, or other modern compilers for transpiling their package.

#### Longer:
The behavior of ES6 is to use `exports.default = ....` for exporting something as default. 
This is equal to using `module.exports = ....` or `module.exports = {...}`.

In ES6 requiring the modules that exported like need explicitly calling `.default`
```js
const x = require(module).default // require(module) is wrong
```

`_require` function in this pull request checks if `default` property exists and returns what it is inside it instead of returning the useless module itself (which will not have the activate function for the package). 

`_require` function checks this phenomenon and adds support for it. Many compilers or bundlers use `_interopDefault` which serves the same purpose. 

### Drawbacks
This function is written pretty conservatively and has no drawbacks.

In Atom, all the packages can only export their functions either named or wrapped in an object. There is no real useful default export that can be called directly. So the mixed situation does not happen, and we can safely merge this PR. 

### Verification
The CI passes

### Release Notes
- Adding support for the packages that export their main functions under an object and are transpiled using modern transpilers (e.g babel 6 or later, etc).

### CODE REVIEW

**Comment by DeeDeeG** [comment]
Just commenting to register that I've seen this. I am not versed with JavaScript or ES versions, and frankly my strong area is in tooling/build troubleshooting (dev ops??), so I can't review the exact implementation here.

But I appreciate the conservative design approach, and I see that CI passes, so that is an approach I can get behind. "RSLGTM", as they say?

I'm not sure what you want to use this with, presumably some ES6 code Atom-side or package-side. So if there is a use-case that would add some context for understanding this, even as a person somewhat ignorant of ES6 such as myself.

(Trying to review or comment on stuff even if I don't have much useful to add.)

**Comment by aminya** [comment]
Thanks for the review. JavaScript is pretty simple. You can learn it [in a day](https://www.youtube.com/watch?v=BwuLxPH8IDs) 😉

**Comment by aminya** [comment]
The upstream PR is made https://github.com/atom/atom/pull/21112. 
Merging this.

**Comment by DeeDeeG** [comment]
I see this is needed for Babel 7. Which is needed for newer Node (12.17+, 14.0.0+).

In which case, great to have this taken care of!

**Comment by DeeDeeG** [comment]
I suppose a non-ES6 could adopt a bad convention, where it exports a "default" module even though it is ES5 or older... Right? And in conjunction with this PR, it could change what is exported and what code is available from the package.

Is this in acceptable risk? Or is that scenario not even problematic? (For instance, I suppose if someone had hypothetically made a "default" module to export, using that one is probably pretty safe.)

**Comment by aminya** [comment]
There is no risk for Atom packages. Atom packages that have exported `activate` function are only loaded using this method. 

For other internal Node requires, we need [babel-plugin-add-module-exports](https://github.com/atom-ide-community/babel-plugin-add-module-exports) which adds:
```js
module.exports = exports.default
```
to the code in some situations. This is included in #65.

**Comment by DeeDeeG** [comment]
Thanks for the explanation and context.

**Pull request merged**
